import assert from "node:assert/strict";
import test from "node:test";

import type { Finding, ReviewItem } from "../src/checks.ts";
import { CREDITS_URL, createReport, humanSummary, PROJECT_URL, TOOL_NAME } from "../src/report.ts";

test("reports carry canonical attribution and credits", () => {
	const report = createReport("/tmp/example", false, { pages: [], stubs: [] }, [], [], false);

	assert.equal(report.toolName, TOOL_NAME);
	assert.equal(report.projectUrl, PROJECT_URL);
	assert.equal(report.creditsUrl, CREDITS_URL);
	assert.match(humanSummary(report), new RegExp(`^Generated by ${TOOL_NAME} — created by Ariel Harlap\\n${PROJECT_URL}`));
});

test("needs-review evidence never becomes a finding or a withheld finding", () => {
	const finding: Finding = {
		what: "Hover text has insufficient contrast.",
		page: "page.html",
		selector: "button",
		evidence: "2.57:1",
		fix: "Increase contrast.",
		lens: "a11y",
		confidence: "medium",
		basis: "WCAG 1.4.3 Contrast (Minimum) (AA)",
		rule: "state-text-contrast",
	};
	const review: ReviewItem = {
		what: "Colour contrast could not be determined automatically.",
		page: "page.html",
		selector: "h2",
		evidence: "background overlap",
		lens: "a11y",
		basis: "WCAG 1.4.3 (AA)",
		rule: "axe:color-contrast",
	};
	const report = createReport(
		"/tmp/example",
		false,
		{ pages: [{ file: "page.html", url: "http://127.0.0.1/page.html" }], stubs: [] },
		[{
			page: { file: "page.html", url: "http://127.0.0.1/page.html" },
			triage: { ok: true },
			audited: true,
			findings: [finding],
			needsReview: [review],
			notes: [],
		}],
		[],
		false,
	);

	assert.equal(report.schemaVersion, 3);
	assert.equal(report.needsReview.length, 1);
	assert.equal(report.counts.needsReview, 1);
	const summary = humanSummary(report, "medium");
	assert.doesNotMatch(summary, /Withheld|people with|affected users/i);
	assert.match(summary, /Location: page\.html — button/);
	assert.match(summary, /Basis: WCAG 1\.4\.3/);
	assert.match(summary, /1 question for a person to review\. It does not count as a finding/);
});
