import assert from 'node:assert/strict';
import { test } from 'node:test';
import { mkdtemp, writeFile, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createHash } from 'node:crypto';
import { scoreRun } from './score.ts';

const hash = (s: string) => createHash('sha256').update(s).digest('hex');
test('manual scoring counts defects once, separates clean false alarms, and validates evidence', async () => {
  const dir = await mkdtemp(join(tmpdir(), 'pdf-score-'));
  const json = (name: string, value: unknown) => writeFile(join(dir,name),JSON.stringify(value));
  try {
    for (const name of ['input.pdf','page.png','facts.json','prompt.md','run.md','generator.py']) await writeFile(join(dir,name),name);
    const manifest = {schemaVersion:'pdf-review-bundle-1',documentSha256:hash('input.pdf'),pageCount:2,selectedPages:[1,2],tier:'visual',artifacts:[1,2].map(page => ({page,image:'page.png',imageSha256:hash('page.png'),facts:'facts.json'}))};
    await json('manifest.json',manifest);
    const finding = {page:1,category:'observed-defect',confidence:'high',message:'Visible overlap',action:'Move text',consequence:'Text obscured',origin:'Inference',verification:'Inspect render',evidence:{observation:'Labels overlap'}};
    const review = {schemaVersion:'pdf-review-2',documentSha256:hash('input.pdf'),tier:'visual',pagesReviewed:[1,2],reviewer:{model:'test-model'},findings:[finding,finding]};
    await json('review.json',review);
    const judgment = {findingIndex:0,verdict:'supported-defect',defectIds:['overlap'],actionable:true,reason:'Visible in synthetic reference'};
    const entry = {id:'flawed',repeat:1,pdfPath:'input.pdf',manifestPath:'manifest.json',reviewPath:'review.json',promptPath:'prompt.md',runPromptPath:'run.md',expectedDefects:[{id:'overlap',category:'layout',page:1},{id:'missing',category:'instructions',page:2}],adjudications:[judgment,{...judgment,findingIndex:1}]};
    const run = {schemaVersion:'pdf-checkeval-1',corpus:{id:'synthetic',version:'1',generatorPath:'generator.py'},model:{id:'test-model',effort:'low'},condition:'baseline',adjudicator:'test-human',cases:[entry]};
    const score = async () => {await json('run.json',run);return scoreRun(join(dir,'run.json'));};
    const result = await score();
    assert.equal(result.totals.detected,1);assert.equal(result.totals.missed,1);
    assert.deepEqual(result.totals.defectDetection,{numerator:1,denominator:2,ratio:0.5});
    assert.equal(result.totals.cleanCaseFalseAlarms.ratio,null);
    assert.equal(result.categories.find(c => c.category === 'instructions')?.missed,1);
    entry.adjudications[1] = {...judgment,findingIndex:0};await assert.rejects(score,/duplicate adjudication/);
    entry.adjudications[1] = {...judgment,findingIndex:1,defectIds:['missing']};await assert.rejects(score,/wrong finding page/);
    entry.adjudications[1] = {...judgment,findingIndex:1,defectIds:['unknown']};await assert.rejects(score,/Unknown defect/);
    entry.adjudications = [judgment];await assert.rejects(score,/Every finding/);
    entry.adjudications = [judgment,{...judgment,findingIndex:1}];
    review.documentSha256 = '0'.repeat(64);await json('review.json',review);await assert.rejects(score,/SHA-256/);
    review.documentSha256 = hash('input.pdf');review.pagesReviewed=[1];await json('review.json',review);await assert.rejects(score,/exactly the bundle/);
    review.pagesReviewed=[1,2];review.reviewer.model='other';await json('review.json',review);await assert.rejects(score,/model or tier/);
    review.reviewer.model='test-model';await json('review.json',review);
    await writeFile(join(dir,'page.png'),'stale');await assert.rejects(score,/image hash/);await writeFile(join(dir,'page.png'),'page.png');
    entry.id='clean';entry.expectedDefects=[];entry.adjudications = [0,1].map(findingIndex => ({...judgment,findingIndex,verdict:'unsupported',defectIds:[]}));
    const clean = await score();assert.equal(clean.totals.unsupportedClaims,2);assert.deepEqual(clean.totals.cleanCaseFalseAlarms,{numerator:1,denominator:1,ratio:1});assert.equal(clean.totals.defectDetection.ratio,null);
    const {category: _category,...v1finding} = finding;
    await json('review.json',{...review,schemaVersion:'pdf-review-1',findings:[v1finding,v1finding]});assert.equal((await score()).totals.unsupportedClaims,2);
    run.cases.push({...entry,repeat:2});const repeated = await score();assert.equal(repeated.totals.trials,2);assert.equal(repeated.totals.uniqueCases,1);assert.equal(repeated.corpus.sha256,clean.corpus.sha256);
    await writeFile(join(dir,'run.md'),'different preprocessing prompt');assert.equal((await score()).corpus.sha256,clean.corpus.sha256);
    await json('bad-verdict.json',{...run,cases:[{...entry,adjudications:entry.adjudications.map(j => ({...j,verdict:['unsupported']}))}]});
    await assert.rejects(scoreRun(join(dir,'bad-verdict.json')),/Invalid adjudication/);
    const withPreprocessing = {...run,cases:run.cases.map(c => ({...c,preprocessingManifestPath:'preprocessing.json'}))};
    await json('preprocessing.json',{scale:2,artifacts:[{path:'page.png',sha256:hash('page.png')}]});
    await json('with-preprocessing.json',withPreprocessing);
    const supplemental = await scoreRun(join(dir,'with-preprocessing.json'));
    assert.match(supplemental.cases[0]!.evidence.preprocessingManifestSha256!,/^[a-f0-9]{64}$/);
    await json('preprocessing.json',{artifacts:[{path:'page.png',sha256:hash('stale')}]});
    await assert.rejects(scoreRun(join(dir,'with-preprocessing.json')),/Preprocessing artifact hash mismatch/);
    const modernManifest = {...manifest,tier:'inference',focus:'visual',checks:['design'],designEvidence:{artifacts:[{path:'facts.json',sha256:hash('facts.json')}]}};
    const modernReview = {...review,schemaVersion:'pdf-review-3',tier:'inference',focus:'visual',checks:['design'],findings:review.findings.map(f => ({...f,check:'design'}))};
    await json('manifest.json',modernManifest);await json('review.json',modernReview);
    assert.equal((await score()).totals.unsupportedClaims,4);
    await json('review.json',{...modernReview,focus:'usability'});await assert.rejects(score,/focus or check domains/);
    await json('review.json',{...modernReview,checks:['accessibility'],findings:modernReview.findings.map(f=>({...f,check:'accessibility'}))});await assert.rejects(score,/focus or check domains/);
    await json('review.json',modernReview);await writeFile(join(dir,'facts.json'),'tampered');await assert.rejects(score,/Design artifact hash mismatch/);
    await writeFile(join(dir,'facts.json'),'facts.json');
    const changedManifest = {...modernManifest,designEvidence:{artifacts:[{path:'prompt.md',sha256:hash('prompt.md')}]}};
    await json('changed-manifest.json',changedManifest);
    const changedRepeat = {...run,cases:[run.cases[0],{...run.cases[1],manifestPath:'changed-manifest.json'}]};
    await json('changed-repeat.json',changedRepeat);
    await assert.rejects(scoreRun(join(dir,'changed-repeat.json')),/Repeated case evidence changed/);
    await json('changed-manifest.json',{...modernManifest,context:{use:'A different task'}});
    await assert.rejects(scoreRun(join(dir,'changed-repeat.json')),/Repeated case evidence changed/);
    const boundManifest = {...modernManifest,schemaVersion:'pdf-review-bundle-2',coverage:'all-pages',artifacts:modernManifest.artifacts.map(a => ({...a,factsSha256:hash('facts.json')}))};
    await json('manifest.json',boundManifest);
    const boundReview = {...modernReview,schemaVersion:'pdf-review-4',bundleSha256:hash(JSON.stringify(boundManifest))};
    await json('review.json',boundReview);
    assert.equal((await score()).totals.unsupportedClaims,4);
    await json('review.json',{...boundReview,bundleSha256:'0'.repeat(64)});
    await assert.rejects(score,/bundle SHA-256/);
    await json('review.json',{...boundReview,pagesReviewed:[1]});
    await assert.rejects(score,/exactly the bundle selected pages/);
    await json('review.json',boundReview);
    entry.manifestPath='.';await assert.rejects(score,/regular file/);
  } finally { await rm(dir,{recursive:true,force:true}); }
});
