import packageJson from "../package.json" with { type: "json" };
import type { CheckResult, Finding, ReviewItem, Triage } from "./checks.ts";
import type { DiscoveredPage, Discovery, RedirectStub } from "./discover.ts";

export const TOOL_NAME = "Praxity Audit";
export const PROJECT_URL = "https://github.com/Praxity/praxity-audit";
export const CREDITS_URL = `${PROJECT_URL}/blob/main/NOTICE.md`;

export interface PageAudit extends CheckResult {
	page: DiscoveredPage;
	triage: Triage;
	audited: boolean;
}

export interface BlockedRequest {
	url: string;
	method: string;
	resourceType: string;
}

interface PageVerdict extends DiscoveredPage {
	triage: Triage;
	audited: boolean;
}

export interface AuditReport {
	schemaVersion: 3;
	toolName: typeof TOOL_NAME;
	toolVersion: string;
	projectUrl: typeof PROJECT_URL;
	creditsUrl: typeof CREDITS_URL;
	target: {
		path: string;
		wasZip: boolean;
	};
	pages: PageVerdict[];
	redirectStubs: RedirectStub[];
	findings: Finding[];
	needsReview: ReviewItem[];
	notes: string[];
	counts: {
		confidence: Record<Finding["confidence"], number>;
		rule: Record<string, number>;
		needsReview: number;
	};
	network: {
		allowed: boolean;
		blockedRequestCount: number;
		blockedRequests: BlockedRequest[];
	};
}

export function createReport(
	targetPath: string,
	wasZip: boolean,
	discovery: Discovery,
	pages: PageAudit[],
	blockedRequests: BlockedRequest[],
	allowNetwork: boolean,
): AuditReport {
	const findings = pages.flatMap((page) => page.findings);
	const needsReview = pages.flatMap((page) => page.needsReview ?? []);
	const notes = pages.flatMap((page) => page.notes);
	const confidence: AuditReport["counts"]["confidence"] = { high: 0, medium: 0, low: 0 };
	const rule: Record<string, number> = {};

	for (const finding of findings) {
		confidence[finding.confidence]++;
		rule[finding.rule] = (rule[finding.rule] ?? 0) + 1;
	}

	return {
		schemaVersion: 3,
		toolName: TOOL_NAME,
		toolVersion: packageJson.version,
		projectUrl: PROJECT_URL,
		creditsUrl: CREDITS_URL,
		target: { path: targetPath, wasZip },
		pages: pages.map(({ page, triage, audited }) => ({ ...page, triage, audited })),
		redirectStubs: discovery.stubs,
		findings,
		needsReview,
		notes,
		counts: { confidence, rule, needsReview: needsReview.length },
		network: {
			allowed: allowNetwork,
			blockedRequestCount: blockedRequests.length,
			blockedRequests,
		},
	};
}

function count(noun: string, amount: number): string {
	return `${amount} ${noun}${amount === 1 ? "" : "s"}`;
}

/**
 * Findings at or above `minConfidence` are shown and drive the exit code.
 * Default is `high`: only measured, unambiguous failures stop a build. Loosen it
 * when the caller wants the medium-confidence custom checks -- focus visibility,
 * focus obscured, non-text contrast, reflow, text spacing -- to count too, which
 * is most of what this tool sees that axe does not.
 */
export type Confidence = "high" | "medium" | "low";
const RANK: Record<Confidence, number> = { high: 3, medium: 2, low: 1 };

export function atOrAbove(level: Confidence, floor: Confidence): boolean {
	return RANK[level] >= RANK[floor];
}

export function countAtOrAbove(report: AuditReport, floor: Confidence): number {
	return report.findings.filter((f) => atOrAbove(f.confidence as Confidence, floor)).length;
}

export function humanSummary(report: AuditReport, minConfidence: Confidence = "high"): string {
	const lines = [
		`Generated by ${report.toolName} — created by Ariel Harlap`,
		report.projectUrl,
		"",
		`Checked ${count("page", report.pages.filter((page) => page.audited).length)}.${report.redirectStubs.length > 0 ? ` Skipped ${count("page", report.redirectStubs.length)} that only redirect elsewhere.` : ""}`,
	];
	const visibleByRule = new Map<string, Finding[]>();

	for (const finding of report.findings) {
		if (!atOrAbove(finding.confidence as Confidence, minConfidence)) continue;
		const group = visibleByRule.get(finding.rule) ?? [];
		group.push(finding);
		visibleByRule.set(finding.rule, group);
	}

	if (visibleByRule.size === 0) lines.push(`No findings at ${minConfidence} or higher confidence.`);
	for (const findings of visibleByRule.values()) {
		const first = findings[0];
		if (!first) continue;
		const pageCount = new Set(findings.map((finding) => finding.page)).size;
		lines.push(
			first.what,
			`  Found ${findings.length === 1 ? "once" : `${findings.length} times`} on ${count("page", pageCount)}.`,
			`  ${findings.length === 1 ? "Location" : "First location"}: ${first.page}${first.selector ? ` — ${first.selector}` : ""}`,
			`  Basis: ${first.basis}`,
		);
	}

	const withheld = report.findings.filter((finding) => !atOrAbove(finding.confidence as Confidence, minConfidence));
	const medium = withheld.filter((finding) => finding.confidence === "medium").length;
	const low = withheld.filter((finding) => finding.confidence === "low").length;
	if (medium > 0 || low > 0) {
		const hidden = [
			medium > 0 ? count("medium-confidence finding", medium) : "",
			low > 0 ? count("low-confidence finding", low) : "",
		].filter(Boolean);
		lines.push(`The JSON report includes ${hidden.join(" and ")} below the selected confidence level.`);
	}
	if (report.needsReview.length > 0) {
		lines.push(`The JSON report contains ${count("question", report.needsReview.length)} for a person to review. ${report.needsReview.length === 1 ? "It does not count as a finding" : "They do not count as findings"}.`);
	}

	const failed = report.pages.filter((page) => !page.triage.ok);
	if (failed.length > 0) {
		lines.push("Pages not checked:");
		for (const page of failed) lines.push(`  ${page.file}: ${page.triage.reason ?? "unknown reason"}`);
	}

	if (report.network.blockedRequestCount > 0) {
		lines.push(`Stopped ${count("internet request", report.network.blockedRequestCount)} from the course. The JSON report lists each one.`);
	}
	for (const note of report.notes) lines.push(`Note: ${note}`);

	return lines.join("\n");
}
